### ISSUE TITLE
Extra <td> being added on payment receipt

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Simple-Shipping#65]
As per the title, an extra `<td></td>` is being added to the payment receipt table.

**Comment by cklosowski** [comment]
this description and title aren't enough to really determine the issue. I've looked at both the purchase receipt as well as the purchase history (since it mentioned table). I cannot find any errant `<td>` tags. If this is still an issue, please re-open with exact details of where this is occurring including screenshots of the markup so we can get a better idea of where this is happening.
