### ISSUE TITLE
Pickup

### ISSUE THREAD

**Issue by nicksarro** [easydigitaldownloads/EDD-Simple-Shipping#72]
Hello, This is a request. I don't know where to go to ask? 

Would it be easy to let a FES vendor choose a shipping cost and to also choose if they'd like to allow pickup for free? So a customer could either choose shipping or to pickup an item?

Thanks :D

**Comment by pippinsplugins** [comment]
Thanks for the suggestion @nicksarro.

Simple Shipping, however, is designed to provide very basic simple functionalities for those people that sell primarily digital products and want to perhaps sell a company tshirt as well.

Due to the nature of Easy _Digital_ Downloads being for digital products, adding more robust shipping options to Simple Shipping is not something we're going to do.

If you're looking for more robust shipping features, we recommend using a physical eCommerce platform that is suited for that purpose.
