### ISSUE TITLE
Add setting for applying taxes to shipping fee

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Simple-Shipping#77]
Original issue on EDD core: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6459
See this comment specifically: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6459#issuecomment-380604030

## Enhancement Request
Add a setting for whether or not taxes should be applied to the shipping fee.

### Justification or use case
By default, taxes apply to the shipping fee. Some users simply do not want that.

### Dev notes from Chris K.

>  I think this should be a Simple Shipping issue. EDD Core already supports altering the tax status of fees. By default the creation of fees (EDD()->fees->add()) sets the no_tax to false. We'd simply need a Simple Shipping setting to state Apply tax on shipping fees, and then have Simple Shipping update to include if tax should be charged, as this is the current call, which defaults to false since no_tax is not specified.
```
EDD()->fees->add_fee( array(
	'amount'      => $amount,
	'label'       => $fee_label,
	'id'          => 'simple_shipping_' . $key,
	'download_id' => $item['id'],
	'price_id'	  => $price_id
) );
```

**Comment by kerijacoby** [comment]
Related tickets: 

https://secure.helpscout.net/conversation/560802469/80312?folderId=180499

https://secure.helpscout.net/conversation/548833379/79126/?folderId=180504

**Comment by cklosowski** [comment]
As a note, by default the existing behavior _does_ charge tax on shipping as the `no_tax` property of feeds defaults to `false`, which means to charge taxes (yay for double negatives).

The above PR, adds a setting to disable taxes on shipping fees, by setting the `no_tax` to `true` when checked. It's a bit confusing but since our existing behavior is to charge taxes on shipping, we need to make this an opt-out as to not affect currently functioning stores behavior unexpectedly.
